name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync
 
    - name: Add EC2 host to known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Sync files to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: | 
        echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ec2_key.pem
        chmod 600 ec2_key.pem
        rsync -avz --delete --exclude='.env' -e "ssh -i ec2_key.pem" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/personal-project---MarketMaster/

    - name: Run Docker Compose on EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/personal-project---MarketMaster/
          docker-compose down
          docker system prune -af
          docker-compose up --build -d
        EOF
